### ISSUE TITLE
Reproducibility of pre-training data

### ISSUE THREAD

**Issue by jordane95** [Veronicium/AnchorDR#1]
Hi, I'm attempting to reproduce your work but find the following two files missing 
```
anchor.tsv      # the file of anchors
web_corpus.tsv  # the file of webpages
```
Can you provide the link to these files? Or can you share the pre-processed pre-training data for reproducibility? Thanks

**Comment by yiqingxyq** [comment]
Hi! These are files in the [ClueWeb-22 dataset.](https://lemurproject.org/clueweb22/docspecs.php) You can find a more detailed description under the "Clean Text (.txt) File Format" and "Inlink (.inlink) File Format" sections.

We also updated README.md. Now it contains the [preprocessed data](https://drive.google.com/file/d/151v1ZB4jjmQ0XfFlRpiYwNvUtEuix5xr/view?usp=sharing) for continuous pretraining. You can refer to [OpenMatch](https://github.com/OpenMatch/OpenMatch) for the training scripts.
